### ISSUE TITLE
"Moving average" least recently used

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaCollections/LRUCache.jl#30]
I was wondering how easy it would be to implement a "moving average" parameter for the LRU cache? Let me explain what I mean with a simple example:

- I have a function `f` which takes integers as input, and performs some complex calculations.
- I know that some integers are very frequently used as input to `f`, while some are one-in-a-million and don't need to be cached.
- Is there a way I can get the LRU cache to update the cache in a slower way, so that the more frequent integers end up taking up the cache, while the one-in-a-million integers are recomputed by `f` each time (and therefore don't kick out the more frequent numbers)?

**Comment by Jutho** [comment]
That sounds like it should be a `LFUCache`, i.e.  `LeastFrequentlyUsedCache`.

**Comment by MilesCranmer** [comment]
Thanks, didn't know the name for it! How hard would it be to add a feature like that? Maybe just a `frecency` (frequently + recently) attribute to LRU which is `Union{Nothing,Dict{K,Int}}` and by default is unused, unless a parameter is set to the constructor which turns on the tracking?

**Comment by Jutho** [comment]
I guessed the name, and then it turned out that this is a well established concept. Because of that, I would actually devise a new type for that, rather than trying to push as much functionality in a single type as possible. The implementation could probably be very similar, though I am also no expert on that. You can always try to duplicate this entire package, change R to F 😄, and change the implementation to keep track of frequencies and reorder the linked list in such a way that it is linked based on frequency.

**Comment by MilesCranmer** [comment]
Thanks! Good idea. Will try this some day in the future when I find time

**Comment by scheidan** [comment]
Just for reference: [`LFUDACache.jl`](https://github.com/OpenSesame/LFUDACache.jl) implements a Least Frequency Used cache.

**Comment by MilesCranmer** [comment]
Thanks! That looks like a solution.
