### ISSUE TITLE
Exceptions in get! may cause lock to not be released

### ISSUE THREAD

**Issue by ghost** [JuliaCollections/LRUCache.jl#31]
I'm using LRUCache 1.3.0 with Julia 1.8.2 (on Windows). To illustrate the problem, unzip the "example.jl" from the attached zip. Then, at the REPL:

```
julia> include("example.jl")
ERROR: LoadError: MethodError: no method matching LRUCache.LinkedNode{Int64}(::Tuple{Int64})
...
julia> include("example.jl")
```
After the second include, the REPL is deadlocked in a call to `empty!` the LRU cache. It looks to me like the `get!` function (and maybe others) in LRUCache.jl should be using try/finally to ensure the lock is released in case of exception.

[example.zip](https://github.com/JuliaCollections/LRUCache.jl/files/9795211/example.zip)

**Comment by ericphanson** [comment]
BTW, I see two functions with this issue: https://github.com/JuliaCollections/LRUCache.jl/blob/9cbd1d1cc888f9c9ff99bd333689137408795357/src/LRUCache.jl#L80-L90

https://github.com/JuliaCollections/LRUCache.jl/blob/9cbd1d1cc888f9c9ff99bd333689137408795357/src/LRUCache.jl#L106-L128

The rest seem to use the do-block form (which can be done without a closure via `@lock` instead, which is exported on Julia 1.9+), which should be safe.

I believe the first can be written as:
```julia
 function Base.get(default::Callable, lru::LRU, key) 
     Base.@lock lru.lock begin
         if _unsafe_haskey(lru, key) 
             return _unsafe_getindex(lru, key) 
         end
     end 
     return default() 
 end 
```
Here, the macro form (or just typing out the finally block) is important, since we don't want to just return from the closure.
Likewise, the second can be written as
```julia
function Base.get!(default::Callable, lru::LRU{K, V}, key) where {K, V} 
    evictions = Tuple{K, V}[] 
    Base.@lock lru.lock begin
        if _unsafe_haskey(lru, key) 
            return _unsafe_getindex(lru, key) 
        end
    end
    v = default() 
    Base.@lock lru.lock begin
        if _unsafe_haskey(lru, key) 
            # should we test that this yields the same result as default() 
            v = _unsafe_getindex(lru, key) 
        else 
            _unsafe_addindex!(lru, v, key) 
            _unsafe_resize!(lru, evictions) 
        end 
    end
    _finalize_evictions!(lru.finalizer, evictions) 
    return v 
end 
```
